name: Create New Test Suite for Release

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch the issue template
        run: |
          echo 'See PR #${{ github.event.number }}' >> .tests/suite1.md
          export TEST_SUITE=$(cat .tests/suite1.md)

      - name: Print Template
        run: echo $TEST_SUITE

      - name: Create Issue for PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const title = '[Test] - Test Suite for Release ${{ github.event.number }}';
            const body = process.env.TEST_SUITE
            github.rest.issues.create({
              owner,
              repo,
              title,
              body
            });
            
